spring:
    datasource:
        url: jdbc:mysql://localhost:3306/my_learning_db?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: create-drop
        show-sql: true
        properties:
            hibernate:
                format_sql: true
    security:
        user:
            name: admin
            password: 123456
application:
    security:
        jwt:
            secret-key: sbACEaVIuNLf49TY5ruzgtsVlZbt9GN/2C71Qi9oq/I=
            expiration: 86400000
            refresh-token:
                expiration: 259200000